### ISSUE TITLE
Please delete this package and use os.arch()

### ISSUE THREAD

**Issue by antonStudentEduUa** [el3um4s/node-adodb#3]
https://github.com/el3um4s/node-adodb/blob/592e1708be49cda49a32da37c576af8055a97f3e/package.json#L41

**Comment by el3um4s** [comment]
[arch](https://www.npmjs.com/package/arch) and [os.arch](https://nodejs.org/dist/latest-v18.x/docs/api/os.html#osarch) are not equivalent.

In Node.js, the `os.arch()` method (and `process.arch` property) returns a string identifying the operating system CPU architecture **for which the Node.js binary was compiled**.

This is not the same as the **operating system CPU architecture**. For example, you can run Node.js 32-bit on a 64-bit OS. In that situation, `os.arch()` will return a misleading 'x86' (32-bit) value, instead of 'x64' (64-bit).
